spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vlpi
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
  security:
    jwt:
      secret-key: MxEtMCRaAjPHcpTy23x3jgbiRq73BUOapk8HmHQsVkMXCyETtsjN5sgFXC3w0wV5hevjTrVe58WRTMwRMI1uaA==
      access-token-expires-in: 86400
logging:
  level:
    org.hibernate.SQL: debug
auditing:
  anonymous-principal: system