spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vlpi
    username: postgres
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true