spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vlpi
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
logging:
  level:
    org.hibernate.SQL: debug